name: CI for NVD scan reusable workflow 

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  nvd_scan:
    uses: yetanalytics/actions/.github/workflows/nvd-scan.yml@d03fa80b39dde4df45698ffd577dcd0c4de2f6b9
    with:
      - notify-slack: true

