name: CI for NVD scan reusable workflow 

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

# Normally this job will output success.
# However we can cause this to fail by uncommenting the log4j dep in deps.edn
jobs:
  nvd_scan:
    uses: yetanalytics/workflow-nvd/.github/workflows/nvd-scan.yml@752da2d99f0399351d58ad1bf1a17743e9d7d7fa
    with:
      notify-slack: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
